print("Give two values to add")
a=int(input())
b=int(input())
c=(a+b)
print(c)
print("my first program")
print('she said : "hello" and then left')
print("she said: \"hello\" and then left")
print('she said: \"hello\" and then left')
print("hello world! \nHello world" )
print("hello" + "Vicky")
print("hello" + " " + "vignesh")
print('e.g. print("Hello" '' "+" "world")')