print("Welcome to the Band Name Generator")
print("What's the name of the city you grew up in?")
a=(input())
print("what's your pet's name?")
b=(input())
print("Your Band Name could be " + a + " " + b) 
